import prompts.draft_email_generating.draft_email_generating_prompt as draft_email_generating_prompt
import prompts.react_agent.react_prompt as react_prompt
import prompts.chatbot.chatbot_prompt as chatbot_prompt
import prompts.order_chatbot.order_chatbot_prompt as order_chatbot_prompt